=== haronbh/XML-Management-with-Python/commande.dtd
<!ELEMENT commande (client, livraison, item+)>
	 <!ATTLIST commande orderid ID #REQUIRED>
    <!ELEMENT client (#PCDATA)>
    <!ELEMENT livraison (adresse, ville, pays)>
    <!ELEMENT adresse (#PCDATA)>
    <!ELEMENT ville (#PCDATA)>
    <!ELEMENT pays (#PCDATA)>
    <!ELEMENT item (libelle, note?, quantite, prix)>
    <!ATTLIST item category (food | games | books) #IMPLIED>
    <!ELEMENT libelle (#PCDATA)>
    <!ELEMENT note (#PCDATA)>
    <!ELEMENT quantite (#PCDATA)>
    <!ELEMENT prix (#PCDATA)>
    <!ATTLIST prix devise (DZD | EUR | USD |YEN) #IMPLIED>

=== haronbh/XML-Management-with-Python/commande_dtd.xml
<?xml version="1.0" encoding ="UTF-8"?>
<!DOCTYPE commande SYSTEM "commande.dtd">
<commande orderid="c9964">
	<client>Yamada Ayu</client>
	<livraison>
		<adresse>380-1299, Mahikizawa</adresse>
		<ville>Tama-shi</ville>
		<pays>Japan</pays>
	</livraison>
	<item category="games">
		<libelle>Wii U</libelle>
		<note> Special Edion </note>
		<quantite> 1 </quantite>
		<prix>900000</prix>
	</item>
	<item category="food">
		<libelle>semoule</libelle>
		<quantite> 10 </quantite>
		<prix devise="DZD">1050</prix>
	</item>
</commande>
